yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
] 

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/',views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/',views.post_detail, name='post_detail'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset_form'),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))

]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, verbose_name='Ссылка')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Содержание')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text

yatube/posts/forms.py
from .models import Post
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields = ( 'text', 'group')

    def clean_text(self):
        data = self.cleaned_data['text']
        if data == '':
            raise forms.ValidationError('Вы обязательно должны ввести текст!')
        return data

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html' 


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'    

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Post, Group, User
from django.contrib.auth.decorators import login_required
from .forms import PostForm
from django.views.generic.edit import CreateView
from django.shortcuts import redirect


LAST_10_POSTS: int = 10

@login_required
def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, LAST_10_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    #    print(Post.objects.filter(pub_date__range=(start_date,end_date)).filter(text__contains=keyword).query) qfwqfqf
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, LAST_10_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all()
    paginator = Paginator(post_list, LAST_10_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_count=user.posts.count()
    context = {
        'post_count':post_count,
        'user': user,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post_more=Post.objects.get(pk=post_id)
    post_count=(post_more.author).posts.count()
    context = {
        'post_more': post_more,
        'post_count': post_count,
    }
    return render(request, 'posts/post_detail.html', context) 


def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            group = form.cleaned_data['group']
            post=form.save(commit=False)
            post.author=request.user
            form.save()
            return redirect('posts:profile', request.user.username)
        return render(request, 'posts/post_create.html', {'form': form})    
    form = PostForm()
    return render(request, 'posts/post_create.html', {'form': form})


def post_edit(request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        form = PostForm(request.POST or None, instance=post)
        if post.author!=request.user:
            return redirect('posts:post_detail', post_id)
        if request.method == "POST":
            form.save()   
        is_edit=True
        context={'form': form,'is_edit':is_edit,'post':post}
        return render(request, 'posts/post_create.html', context)    
    

yatube/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Привет, я Мишаня</h1>
      <p class="lead">  Тут я размещу информацию о себе, используя свои умения верстать.
        Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста.
      </p>
  </div>
</div>    
<p>
  <div class="card" style="width: 18rem;">
    <img src="https://i12.fotocdn.net/s123/19e8071823e2e840/public_pin_l/2810595319.jpg" 
        class="card-img-top"
        alt="https://steamsolo.com/wp-content/uploads/2021/07/how-to-make-a-multi-colored-nametag-stellaris.jpg"
        >
    <div class="card-body">
      <p class="card-text">Тут я вставлю картинку из интерета, потому что умею.</p>
    </div>
  </div>
</p>
<p>
  <div class="card">
    <div class="card-header">
          Ауф-цитаты в помощь
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>Иногда жизнь — это жизнь, а ты в ней иногда.</p>
          <footer class="blockquote-footer">Что-то полезное в <cite title="Source Title">бесполезном.</cite></footer>
          </blockquote>
    </div>
  </div>
</p>
<div class="card w-75">
  <div class="card-body">
    <h5 class="card-title">А тут мой гитхуб</h5>
    <a href="https://github.com/DeLaMia" class="btn btn-primary">Жнопка</a>
  </div>
</div>    
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
      <li class="list-group-item">
        Есть
      </li>
      <li class="list-group-item">
        Спать
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
          <h5 class="card-title">Все что умею ищите на моем гитхубе.</h5>
          <a href="https://github.com/DeLaMia" class="btn btn-primary">Переход куда-нибудь</a>
      </div>
    </div>
  </article>
  <div class="d-flex align-items-center">
    <strong>Думаю что еще бы вставить, но не придумал...</strong>
    <div class="spinner-border text-right" role="status" aria-hidden="true"></div>
  </div>
</div>
{% endblock %} 

yatube/templates/base.html
{% load static %} <!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <meta name="description" content={{ text }}>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>{% include "includes/header.html" %}</header>
    <main>{% block content %}{% endblock %}</main>
    <footer class="border-top text-center py-3">
      {% include "includes/footer.html" %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color: red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{%  url 'posts:index' %}">
      <img
        src="{% static 'img/logo.png' %}"
        width="30"
        height="30"
        class="d-inline-block align-top"
        alt="" />
      <span style="color: red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %} 
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:password_reset_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
      {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
      {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

yatube/templates/includes/post_card.html
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }} 
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя </a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  <p>
  {% if post.pk %}
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
  {% endif %}
  </p>    
</article>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>   
    {% for post in page_obj %}
      {% include "includes/post_card.html" %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <h1>Последние обновления на сайте</h1>  
      {% for post in page_obj %}
        {% include "includes/post_card.html" %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
  </div>   
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% block title %}Новый пост{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать пост  
          {% else %}
            Новый пост
          {% endif %} 
        </div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              
              <form method="post" action="{% url 'posts:post_create' %}">
              {% csrf_token %}            
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Текст поста                  
                    <span class="required text-danger" >*</span>                  
                  </label>
                  {{ form.text|addclass:'form-control' }} 
                  <small id="id_text-help" class="form-text text-muted">
                    Текст нового поста
                  </small>                  
                </div>            
                <div class="form-group row my-3 p-3">
                  <label for="id_group">
                    Группа                  
                  </label>
                  {{form.group|addclass:'form-control'}}
                  <small id="id_group-help" class="form-text text-muted">
                    Группа, к которой будет относиться пост
                  </small>
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}               
                  </button> 
                </div>
              </form>
          </div> 
        </div> 
      </div> 
  </div> 
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост   {{ post_more.text|truncatechars:30 }}{% endblock %}
{% block content %}
<main>
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{post_more.pub_date}}
        </li>
        {% if post_more.group %}
          <li class="list-group-item">
            Группа: {{post_more.group}}
            <a href="{% url 'posts:group_list' post_more.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{post_more.author}}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span> {{post_count}}</span>
        </li>
        {% if post_more.author %}
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post_more.author %}">все посты пользователя </a>   
          </li>
        {% endif %}
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
      {{post_more.text}}
      </p>
      {% if post_more.author == user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post_more.id %}">
          редактировать запись
        </a> 
      {% endif %}
    </article>
  </div> 
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя  {{ user.username }}{% endblock %}
{% block content %}
<div class="container py-5">        
  <h1>Все посты пользователя {{user.username}} </h1>
  <h3>Всего постов: {{post_count}} </h3>   
  <article>
    <p>
      {% for post in page_obj %}
        {% include "includes/post_card.html" %}    
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </p>
  </article>          
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> 
    </div> 
  </div> 
</div> 
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %} 

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              
              <form method="post" action="{% url 'users:signup' %}">
                {% csrf_token %}
                {% for field in form %} 
                  <div class="form-group row my-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                        {% if field.field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {{ field|addclass:'form-control' }} 
                      {% if field.help_text %}
                        <small 
                           id="{{ field.id_for_label }}-help"
                           class="form-text text-muted"
                        >
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                  </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    Зарегистрироваться
                  </button>
                </div>
              </form>
          </div> 
        </div> 
      </div> 
  </div> 
{% endblock %} 